/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.62
 * Generated at: 2015-06-03 08:14:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class firstpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en-US\">\n");
      out.write("<script src=\"http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js\"></script>\n");
      out.write("<script src=\"http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular-resource.js\"></script>\n");
      out.write("<body ng-app=\"myApp\">\n");
      out.write("<h2>Item List</h2>\n");
      out.write("<div ng-controller=\"myCtrl1\">\n");
      out.write("  <ul>\n");
      out.write("    <li ng-repeat=\"x in items.item\">\n");
      out.write("        {{x.productname+\" \"+x.quantity}}    \n");
      out.write("    </li>\n");
      out.write("  </ul>\n");
      out.write("  <h2>Add Item</h2>\n");
      out.write("  <p>Product Name : <input type=\"text\" ng-model=\"productname\">\n");
      out.write("  Quantity : <input type=\"text\" ng-model=\"quantity\"></p>\n");
      out.write("  <p><input type=\"button\" id=\"adddetails\" value=\"ADD\" ng-click=\"addNames()\"/>\n");
      out.write("  <input type=\"button\" id=\"getdata\" value=\"GET DATA\" ng-click=\"getData()\"/></p> \n");
      out.write("  <p><input type=\"button\" id=\"update\" value=\"UPDATE\" ng-click=\"updateProduct()\"/>   \n");
      out.write("  <input type=\"button\" id=\"updateList\" value=\"UPDATE LIST\" ng-click=\"updateProductList()\"/></p> \n");
      out.write("  <p>Data from service : {{message}}</p>\n");
      out.write("  <p>Updated products : {{product}}</p>\n");
      out.write("  <p>Updated product List</p>\n");
      out.write("  <table>\n");
      out.write("  \t<tr ng-repeat=\"prod in products.item\">\n");
      out.write("  \t\t<td>{{prod.productname}}</td>\n");
      out.write("  \t\t<td>{{prod.quantity}}</td>\n");
      out.write("  \t</tr>\n");
      out.write("  </table>\n");
      out.write("</div>\n");
      out.write("<script src=\"productmanipulatescipt.js\">\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html> ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
